// AUTO-GENERATED by scripts/inject-version.ts — do not edit (this is the dev stub).
export const BUNDLE_VERSION = '0.15.0';
export const WORKER_HASH = 'sha256:19755b702b37f6b4add616c2945b74b358ab2a95478a5da95ea7d1a1766574e8';
export const ADMIN_HASH = 'sha256:df4b741409059dc4a05f7f07ba82fd54cf21dbc7773edd0baf26c76dd2acf411';
export const LIFF_HASH = 'sha256:33f062b9754b025ccaa4a8a73ef2f99434f286738ac3ad6c539cb8681c6586f0';
export const RELEASED_AT = '2026-06-07T08:47:02.893Z';
