const GENERATED_MARKER =
  "# Generated by create-line-harness. Safe to overwrite on future setup runs.";

const DEFAULT_MANIFEST_URL =
  "https://github.com/Shudesu/line-harness-oss/releases/latest/download/release-manifest.json";

export interface SavedInstallConfig {
  projectName?: string;
  workerName?: string;
  adminProject?: string;
  adminUrl?: string;
  workerUrl?: string;
  d1DatabaseId?: string;
  d1DatabaseName?: string;
  r2BucketName?: string;
  accountId?: string;
  cfAccountId?: string;
  manifestUrl?: string;
  workerPublicUrl?: string;
  adminPublicUrl?: string;
  liffProject?: string;
  liffPublicUrl?: string;
}

export interface InstalledWranglerConfig {
  workerName: string;
  accountId: string;
  d1DatabaseName: string;
  d1DatabaseId: string;
  r2BucketName: string;
  workerPublicUrl: string;
  adminPagesProject: string;
  adminPublicUrl: string;
  liffPagesProject: string;
  liffPublicUrl: string;
  manifestUrl: string;
}

export function isGeneratedInstalledWranglerToml(content: string): boolean {
  return content.includes(GENERATED_MARKER);
}

export function resolveInstalledWranglerConfig(
  config: SavedInstallConfig,
): InstalledWranglerConfig | null {
  const workerName = config.workerName ?? config.projectName;
  const accountId = config.cfAccountId ?? config.accountId;
  const d1DatabaseId = config.d1DatabaseId;
  const d1DatabaseName = config.d1DatabaseName ?? config.projectName;
  const r2BucketName =
    config.r2BucketName ??
    (config.projectName ? `${config.projectName}-images` : undefined);
  const workerPublicUrl = config.workerPublicUrl ?? config.workerUrl;

  let adminPagesProject = config.adminProject;
  if (!adminPagesProject && typeof config.adminUrl === "string") {
    try {
      adminPagesProject = new URL(config.adminUrl).hostname.replace(
        /\.pages\.dev$/,
        "",
      );
    } catch {
      // Ignore parse errors and fall through to null.
    }
  }

  const adminPublicUrl = config.adminPublicUrl ?? config.adminUrl;
  const liffPagesProject = config.liffProject ?? `${workerName ?? "line-harness"}-liff`;
  const liffPublicUrl = config.liffPublicUrl ?? workerPublicUrl;

  if (
    !workerName ||
    !accountId ||
    !d1DatabaseId ||
    !d1DatabaseName ||
    !r2BucketName ||
    !workerPublicUrl ||
    !adminPagesProject ||
    !adminPublicUrl ||
    !liffPublicUrl
  ) {
    return null;
  }

  return {
    workerName,
    accountId,
    d1DatabaseName,
    d1DatabaseId,
    r2BucketName,
    workerPublicUrl,
    adminPagesProject,
    adminPublicUrl,
    liffPagesProject,
    liffPublicUrl,
    manifestUrl: config.manifestUrl ?? DEFAULT_MANIFEST_URL,
  };
}

export function renderInstalledWranglerToml(
  config: InstalledWranglerConfig,
): string {
  return `${GENERATED_MARKER}
name = "${config.workerName}"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "${config.accountId}"

[assets]
directory = "dist/client"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "${config.d1DatabaseName}"
database_id = "${config.d1DatabaseId}"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "${config.r2BucketName}"

[triggers]
crons = ["*/5 * * * *", "0 */6 * * *"]

[vars]
WORKER_NAME = "${config.workerName}"
ADMIN_PAGES_PROJECT = "${config.adminPagesProject}"
LIFF_PAGES_PROJECT = "${config.liffPagesProject}"
D1_DATABASE_ID = "${config.d1DatabaseId}"
MANIFEST_URL = "${config.manifestUrl}"
WORKER_PUBLIC_URL = "${config.workerPublicUrl}"
ADMIN_PUBLIC_URL = "${config.adminPublicUrl}"
LIFF_PUBLIC_URL = "${config.liffPublicUrl}"
CF_ACCOUNT_ID = "${config.accountId}"
`;
}
